### PR TITLE
Updated to v. 0.6.0

### PR DESCRIPTION
**Pull request by damko**
Hello, thank you for your spark

I updated the google API to v.0.6.0

ciao!

### CODE REVIEW

**Comment by damko** [comment]
I made a little mess with the commits but it's just a plain replacement. I also added tag 0.6.0

**Comment by joeauty** [comment]
Thanks damko! I haven't had a chance to test 0.6.0 yet, but I at least updated the spark.info and README file to reflect the new version, and will notify getsparks as well.

I appreciate your help with this Spark, such that it is!

**Comment by damko** [comment]
you are more than welcome. I'm currently trying v.0.6.0 ... wish me good luck :)

**Comment by joeauty** [comment]
I'd be interested in taking a look at your project, if it is intended 
for public consumption!

Damiano Venturin wrote:

> you are more than welcome. I'm currently trying v.0.6.0 ... wish me good
> luck :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joeauty/Google-API-Client-CodeIgniter-Spark/pull/1#issuecomment-11982096.

## 

Joe Auty, NetMusician
NetMusician helps musicians, bands and artists create beautiful,
professional, custom designed, career-essential websites that are easy
to maintain and to integrate with popular social networks.
www.netmusician.org http://www.netmusician.org
joe@netmusician.org mailto:joe@netmusician.org

**Comment by damko** [comment]
well, all my project are intended for public consumption :) I'm an open source guy. Which project are you referring to? one of those listed in my github home page or this one in which I'm using your spark?

**Comment by joeauty** [comment]
Both! I'm always interested in connecting with fellow developers into 
similar technologies. I've found that sometimes these can even lead to 
work and/or new projects :)

Damiano Venturin wrote:

> well, all my project are intended for public consumption :) I'm an open
> source guy. Which project are you referring to? one of those listed in
> my github home page or this one in which I'm using your spark?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joeauty/Google-API-Client-CodeIgniter-Spark/pull/1#issuecomment-11982362.

## 

Joe Auty, NetMusician
NetMusician helps musicians, bands and artists create beautiful,
professional, custom designed, career-essential websites that are easy
to maintain and to integrate with popular social networks.
www.netmusician.org http://www.netmusician.org
joe@netmusician.org mailto:joe@netmusician.org

**Comment by damko** [comment]
sure, you are more than welcome.

About your Spark, I'm trying to hook google groups API to see if I can use that service in a different UI

About my other projects probably the most triggering are:

1) Contact Engine https://github.com/damko/Contact-Engine
2) MCB-SB  https://github.com/damko/MyClientBase-SB
3) Tooljar http://tooljar.biz

About Tooljar I'm really in need of qualified beta testers. With qualified I mean actually IT savy people who wants to give a hand and then leverage on the tool to offer new services to their customers

If you prefer to go on with the discussion in a different place just hook me on gtalk or by email (my mail should be visible on my profile)

Ciao!

**Pull request merged**
